[workspace]
members = [
  "core",
  "storage",
  "backend",
  "backend/backend-types",
  "frontend/shengji-wasm"
]

[profile.release]
lto = true

[profile.release.package."shengji-wasm"]
opt-level = 'z'
